# Generated by Django 4.0.1 on 2023-05-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='studentimg',
            field=models.ImageField(default='/static/images.png/', upload_to='images/'),
        ),
    ]
