# Generated by Django 4.0.1 on 2023-05-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_alter_userdetail_studentimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='studentimg',
            field=models.ImageField(default='images.png/', upload_to='images/'),
        ),
    ]
